on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googlesheets4
            any::glue
            any::httr
            any::dplyr
            any::jsonlite
            any::purrr
            any::tidyr
            any::tibble
            any::rvest
            any::stringr
            any::R6
            any::futile.logger
            any::logging
            any::reshape2

      - name: Import data
        run: |
          Rscript -e 'source("R/classOddsScrapper.R")'
